### ISSUE TITLE
ContentLimit by time

### ISSUE THREAD

**Issue by jb-alvarado** [BourgondAries/file-rotate#12]
Hello,
I found your nice lib and wanted to use it in my project, but I would need the function log rotated by time. Do you see any chance to integrate this?

For example rotate every midnight. Or even better to give a specific time: every day at 6 in the morning.

Have a good day!

**Comment by Ploppz** [comment]
Definitely sounds like something we should support! The question is how.
We assume that the FileRotate object can be dropped and re-initialized at any points in time (because the application using it might be killed and restart, and might be down for any amount of time).

I can think of two ways to implement this.

Solution 1: store the last rotation time in some file (hidden? like `.file-rotate`). This is read only on initialization of `FileRotate`, and written to every time we rotate.
Solution 2: whenever writing to file, is it possible and economical to check in the file metadata the timestamp of the previous write? If so we can implement "rotate at a specific time(s) every day" by checking whether the previous write was _before_ the desired time of rotation. But this alone does not suffice if we want to support arbitrary `Duration` intervals between rotation. Then we will have to remember the last time of rotation as in Solution 1.

Maybe my analysis is lacking, so I welcome any thoughts about this. I don't have time at this moment to implement it but might do it in not too long.

**Comment by jb-alvarado** [comment]
I think it helps to look what the python [TimedRotatingFileHandler](https://github.com/python/cpython/blob/7fce1063b6e5a366f8504e039a8ccdd6944625cd/Lib/logging/handlers.py#L202) does. It uses st_mtime − time of most recent content modification.
